name: Scheduled Build

on:
  repository_dispatch: # For triggering rebuilds via webhooks
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy.yml
